version: '3.8'

services:
  sticker2img-bot:
    build: .
    image: aiastia/mytgbot:sticker2img
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - BOT_TOKEN=${BOT_TOKEN}
    logging:
      options:
        max-size: "10m"
        max-file: "3"