version: '3.8'

services:
  tgpattern:
    image: aiastia/mytgbot:code
    volumes:
      - ./data:/app/data/
    restart: unless-stopped    
    environment:
      - TZ=Asia/Shanghai
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_IDS=123456789
    logging:
      options:
        max-size: "10m"
        max-file: "3"
