# Telegram API Configuration
api_id: 123456
api_hash: "your_api_hash_here"

# Multi-Account Configuration
accounts:
  - name: "account1"  # 账户名称，用于区分不同账户
    session_name: "bot_session_1"  # 会话文件名
    enabled: true  # 是否启用此账户
    admin_ids: []  # 此账户的管理员ID列表
    monitoring:
      enabled_chats: []  # 此账户监控的聊天ID列表
      monitor_private_bots: true  # 是否监控与机器人的私聊
      bot_usernames: []  # 要监控的机器人用户名列表，为空则监控所有机器人
      auto_forward_media: true  # 是否自动转发媒体文件（不需要关键词）
    keywords: []  # 此账户的关键词列表
    forwarding:
      rules: []  # 此账户的转发规则
      fallback_to_upload: true  # 转发失败时是否尝试重新上传
    storage:
      download_path: "./downloads/account1"  # 此账户的下载路径
      auto_download: true
      file_naming: "{chat_id}_{message_id}_{timestamp}_{filename}"  # 文件命名格式

  - name: "account2"
    session_name: "bot_session_2"
    enabled: false
    admin_ids: []
    monitoring:
      enabled_chats: []
      monitor_private_bots: true
      bot_usernames: []
      auto_forward_media: true
    keywords: []
    forwarding:
      rules: []
      fallback_to_upload: true
    storage:
      download_path: "./downloads/account2"
      auto_download: true
      file_naming: "{chat_id}_{message_id}_{timestamp}_{filename}"

# Database Configuration
database:
  url: "sqlite:///bot.db"

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "bot.log"

# Storage Configuration
storage:
  download_path: "storage/downloads"
  auto_download: false  # 是否自动下载文件
  # File naming format: {chat_id}_{message_id}_{timestamp}_{filename}
  file_naming: "{chat_id}_{message_id}_{timestamp}_{filename}"

# Monitoring Configuration
monitoring:
  enabled_chats: []  # List of chat IDs to monitor
  keywords: []  # List of keywords to monitor
  case_sensitive: false

# Forwarding Configuration
forwarding:
  rules: []  # List of forwarding rules
  # Fallback to download and re-upload if direct forward fails
  fallback_to_upload: true 