version: '3.8'

services:
  tgpattern:
    image: aiastia/mytgbot:mpt
    volumes:
      - ./data:/app/data/
      - ./config.yaml:/app/config.yaml
    restart: unless-stopped    
    environment:
      - TZ=Asia/Shanghai
    logging:
      options:
        max-size: "10m"
        max-file: "3"
