version: '3.8'

services:
  tgpattern:
    image: aiastia/mytgbot:115
    volumes:
      - ./data:/app/data/
      - ./user_tokens:/app/user_tokens/
    restart: unless-stopped    
    environment:
      - TZ=Asia/Shanghai
      - BOT_TOKEN=****:******
      - CLIENT_ID=100195135
      - USER_TOKEN_DIR=user_tokens
      - ADMIN_IDS=123456789
      - LOG_LEVEL=INFO
    logging:
      options:
        max-size: "10m"
        max-file: "3"
